import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import {Header} from "@/components/Header";
import {cn} from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });
const anekTelugu = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className,anekTelugu.className,'antialiased','')}>
      {children}
      </body>
    </html>
  );
}
